[package]
name = "euc_lib"
version = "0.2.5"
edition = "2021"
license = "GPL-3.0"
license_file="LICENSE"
description="Easy to use implementation of extended and normanl Euclidean algorithm"

[lib]
name = "euc_lib"
path = "./src/lib.rs"
crate-type = ["lib"]

[dependencies]
